---
# - name: Install Kubernetes
#  hosts: HOME
#  roles:
#  - kubeadm

# - name: Reset cluster
#   hosts: ALLNODES
#   roles:
#   - Resetcluster

- name: Init cluster
  hosts: localhost
  roles:
  - Installcalico
